[package]
name = "signature-generator"
version = "0.1.0"
authors = ["Nils <nils@nilsand.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.6.0"
hex = "0.4.2"
hex-literal = "0.3.1"
block-modes = "0.7.0"
